<testsuite errors="1" failures="2" name="" skips="0" tests="3" time="9.6903860569"><testcase classname="TestAccountInformation" name="test_list_tickets_and_verify_the_account_data" result="FAILED"><failure message="None != False" type="AssertionError">Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/CloudCafeTest/workspace/lib/testrepo/tq_search/search_existing_ticket/test_account_information.py", line 70, in test_list_tickets_and_verify_the_account_data
    high_profile_value)
AssertionError: None != False
</failure></testcase><testcase classname="TestAccountInformation" name="test_same_number_of_accounts_in_account_svs_and_elastic_search" result="FAILED"><failure message="The number of accounts are not same in elastic                           search and account services" type="AssertionError">Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/CloudCafeTest/workspace/lib/testrepo/tq_search/search_existing_ticket/test_account_information.py", line 248, in test_same_number_of_accounts_in_account_svs_and_elastic_search
    search and account services")
AssertionError: '290826' != '348873' : The number of accounts are not same in elastic                           search and account services
</failure></testcase><testcase classname="TestAccountInformation" name="test_updating_team_attribute_from_account_services_doesnt_showup_in_tq_search" result="ERROR"><error message="'NoneType' object has no attribute 'team'" type="AttributeError">Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/CloudCafeTest/workspace/lib/testrepo/tq_search/search_existing_ticket/test_account_information.py", line 196, in test_updating_team_attribute_from_account_services_doesnt_showup_in_tq_search
    initial_team_name = get_account_info_from_acc_svs.team
AttributeError: 'NoneType' object has no attribute 'team'
</error></testcase></testsuite>